import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getCustomerJob } from './customerPortalService.js';
import { formatCustomerDateTime, formatCustomerQuantity, getCustomerPortalErrorMessage } from './customerPortalUtils.js';

export default function CustomerJobDetailPage() {
  const { jobId } = useParams();
  const [state, setState] = useState({ loading: true, data: null, error: '' });
  useEffect(() => { const controller = new AbortController(); getCustomerJob(jobId, { signal: controller.signal }).then((data) => setState({ loading: false, data, error: '' })).catch((error) => { if (error?.name !== 'AbortError') setState({ loading: false, data: null, error: getCustomerPortalErrorMessage(error, 'el trabajo') }); }); return () => controller.abort(); }, [jobId]);
  if (state.loading) return <section className="customer-state" role="status" aria-live="polite"><span className="customer-loader" /><p>Cargando trabajo…</p></section>;
  if (state.error) return <section className="customer-state customer-state--error" role="alert"><h1>Trabajo no disponible</h1><p>{state.error}</p><Link to="/customer/service-history">Volver al historial</Link></section>;
  const job = state.data;
  return <section className="customer-page"><nav className="customer-breadcrumb" aria-label="Ruta de navegación"><Link to={`/customer/work-orders/${job.workOrderId}`}>Orden #{job.workOrderId}</Link><span>/</span><strong>Trabajo #{job.jobId}</strong></nav><header className="customer-page__heading"><div><span>Trabajo</span><h1>{job.vehicle.label}</h1></div><span className="customer-status">{job.visibleStatus}</span></header><article className="customer-card"><dl className="customer-detail-grid"><div><dt>Fecha programada</dt><dd>{formatCustomerDateTime(job.scheduledStartDate)}</dd></div><div><dt>Inicio real</dt><dd>{formatCustomerDateTime(job.actualStartDate)}</dd></div><div><dt>Finalización</dt><dd>{formatCustomerDateTime(job.actualEndDate)}</dd></div><div><dt>Técnico</dt><dd>{job.technicianName || 'Por asignar'}</dd></div><div><dt>Especialidad</dt><dd>{job.technicianSpecialty || 'No registrada'}</dd></div></dl></article><article className="customer-card customer-section"><header className="customer-card__header"><div><h2>Servicios realizados</h2><p>Importes finales disponibles en el reporte de servicio.</p></div></header>{job.services.length === 0 ? <div className="customer-state customer-state--inside"><p>No hay servicios registrados.</p></div> : <ul className="customer-line-list">{job.services.map((line, index) => <li key={`${line.serviceName}-${index}`}><strong>{line.serviceName}</strong><span>{formatCustomerQuantity(line.quantity)}</span></li>)}</ul>}<header className="customer-card__header"><div><h2>Piezas utilizadas</h2></div></header>{job.parts.length === 0 ? <div className="customer-state customer-state--inside"><p>No hay piezas registradas.</p></div> : <ul className="customer-line-list">{job.parts.map((line, index) => <li key={`${line.partName}-${index}`}><strong>{line.partName}</strong><span>{formatCustomerQuantity(line.quantity)}</span></li>)}</ul>}<p className="customer-notice">El total final se mostrará en el Reporte de Servicio cuando esté disponible.</p></article><Link className="customer-back-link" to={`/customer/quotations/${job.quotationWorkOrderId}`}>Ver cotización relacionada</Link></section>;
}
