import { useEffect, useState } from 'react';
import { Link, useParams } from 'react-router-dom';
import { getCustomerQuotation } from './customerPortalService.js';
import { formatCustomerDateTime, formatCustomerMoney, formatCustomerQuantity, getCustomerPortalErrorMessage } from './customerPortalUtils.js';

function Lines({ title, items, type, currency }) {
  return <section className="customer-lines"><h2>{title}</h2>{items.length === 0 ? <p>No hay líneas registradas.</p> : <div className="customer-table-wrap"><table className="customer-table"><caption className="customer-visually-hidden">{title}</caption><thead><tr><th>{type}</th><th>Descripción</th><th>Cantidad</th><th>Precio unitario</th><th>Importe</th></tr></thead><tbody>{items.map((line, index) => <tr key={`${line.serviceName ?? line.partName}-${index}`}><td><strong>{line.serviceName ?? line.partName}</strong>{line.partNumber && <small>{line.partNumber}</small>}</td><td>{line.description || 'Sin descripción'}</td><td>{formatCustomerQuantity(line.quantity)}</td><td>{formatCustomerMoney(line.unitPrice, currency)}</td><td>{formatCustomerMoney(line.lineTotal, currency)}</td></tr>)}</tbody></table></div>}</section>;
}

export default function CustomerQuotationDetailPage() {
  const { workOrderId } = useParams();
  const [state, setState] = useState({ loading: true, data: null, error: '' });
  useEffect(() => { const controller = new AbortController(); getCustomerQuotation(workOrderId, { signal: controller.signal }).then((data) => setState({ loading: false, data, error: '' })).catch((error) => { if (error?.name !== 'AbortError') setState({ loading: false, data: null, error: getCustomerPortalErrorMessage(error, 'la cotización') }); }); return () => controller.abort(); }, [workOrderId]);
  if (state.loading) return <section className="customer-state" role="status" aria-live="polite"><span className="customer-loader" /><p>Cargando cotización…</p></section>;
  if (state.error) return <section className="customer-state customer-state--error" role="alert"><h1>Cotización no disponible</h1><p>{state.error}</p><Link to="/customer/quotations">Volver a cotizaciones</Link></section>;
  const quote = state.data;
  return <section className="customer-page"><nav className="customer-breadcrumb" aria-label="Ruta de navegación"><Link to="/customer/quotations">Cotizaciones</Link><span>/</span><strong>Orden #{quote.workOrderId}</strong></nav><header className="customer-page__heading"><div><span>Revisión {quote.revisionNumber}</span><h1>Cotización</h1></div><span className="customer-status">{quote.visibleStatus}</span></header><article className="customer-card"><dl className="customer-detail-grid"><div><dt>Inicio estimado</dt><dd>{formatCustomerDateTime(quote.estimatedStartDate)}</dd></div><div><dt>Entrega estimada</dt><dd>{formatCustomerDateTime(quote.estimatedDeliveryDate)}</dd></div><div><dt>Horas estimadas</dt><dd>{formatCustomerQuantity(quote.estimatedHours)}</dd></div><div><dt>Moneda</dt><dd>{quote.currency}</dd></div><div><dt>Notas</dt><dd>{quote.customerNotes || 'Sin notas para el cliente'}</dd></div>{quote.acceptedAt && <div><dt>Aceptación registrada</dt><dd>{formatCustomerDateTime(quote.acceptedAt)}{quote.acceptanceMethod ? ` · ${quote.acceptanceMethod}` : ''}</dd></div>}</dl></article><article className="customer-card customer-section"><Lines title="Servicios cotizados" items={quote.services} type="Servicio" currency={quote.currency} /><Lines title="Piezas cotizadas" items={quote.parts} type="Pieza" currency={quote.currency} /><dl className="customer-totals"><div><dt>Subtotal</dt><dd>{formatCustomerMoney(quote.subtotal, quote.currency)}</dd></div><div><dt>IVA {quote.applyIva ? `(${formatCustomerQuantity(Number(quote.ivaRate) * 100)}%)` : '(no aplicado)'}</dt><dd>{formatCustomerMoney(quote.ivaAmount, quote.currency)}</dd></div><div><dt>Total</dt><dd>{formatCustomerMoney(quote.total, quote.currency)}</dd></div></dl></article></section>;
}
